#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : toolbelt
Version  : 0.8.0
Release  : 8
URL      : https://github.com/requests/toolbelt/archive/0.8.0.tar.gz
Source0  : https://github.com/requests/toolbelt/archive/0.8.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: toolbelt-python3
Requires: toolbelt-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest

BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : tox
BuildRequires : virtualenv

%description
requests toolbelt
=================
This is just a collection of utilities for `python-requests`_, but don't
really belong in ``requests`` proper. The minimum tested requests version is
``2.1.0``. In reality, the toolbelt should work with ``2.0.1`` as well, but
some idiosyncracies prevent effective or sane testing on that version.

%package python
Summary: python components for the toolbelt package.
Group: Default
Requires: toolbelt-python3

%description python
python components for the toolbelt package.


%package python3
Summary: python3 components for the toolbelt package.
Group: Default
Requires: python3-core

%description python3
python3 components for the toolbelt package.


%prep
%setup -q -n toolbelt-0.8.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1523309235
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
